### ISSUE TITLE
panic: load: can't create DataFrame from empty slice

### ISSUE THREAD

**Issue by Sugimoto-Dev** [gsxhnd/garage#24]
garage version 0.0.12

```shell
❯ ./garage crawl_javbus javbus_code JUQ-556
2024-12-20T03:59:17.663890+00:00	INFO	garage_jav/javbus.go:53	Visiting: https://www.javbus.com/JUQ-556
panic: load: can't create DataFrame from empty slice

goroutine 1 [running]:
main.main()
	github.com/gsxhnd/garage/garage_cmd/main.go:29 +0x56
```

怀疑是触发了网站的年龄检测.

用curl测试了一下, 未添加任何http header, 可以正常获取html.

![CleanShot 2024-12-20 at 12 18 57@2x](https://github.com/user-attachments/assets/56ddd002-09b0-4916-a789-32c67a3fc1ee)

之后用go测试了一下,  结果如下

![CleanShot 2024-12-20 at 12 15 16@2x](https://github.com/user-attachments/assets/647cd85e-a306-4451-ba4b-d5bc43842d68)

尝试添加了可正常浏览bus网页的浏览器cookie到request中结果相同, 没弄清缺了什么参数.

**Comment by gsxhnd** [comment]
可能是重定向到年龄检测页面，也有可能是cloudflare 拦截了

**Comment by sabahmax-dev** [comment]
Thanks for the detailed report! I’ve opened [PR #25](https://github.com/gsxhnd/garage/pull/25), which fixes this panic by handling the case where the page returns no parseable data and returning a clear error message instead of crashing.
